### PR TITLE
Ported to VS2019

### PR DESCRIPTION
**Pull request by DrEthan77**
updated all of the references, removed some obsolete things, referenced the correct VS versions.

### CODE REVIEW

**Comment by DrEthan77** [comment]
btw i have tested this on my vs2019 install and it works just fine.

**Comment by DrEthan77** [comment]
[TabSanity_vsix.zip](https://github.com/jedmao/tabsanity-vs/files/3099657/TabSanity_vsix.zip)

**Comment by jedmao** [comment]
Published on the Marketplace. Thanks!

**Comment by MarkRobinsonHERE** [comment]
Looks like these changes have broken support in VS2017. It no longer works.

**Comment by DrEthan77** [comment]
@MarkRobinsonHERE @jedmao yeah, there is no way around that, so many of the things required to run this plugin for VS2019 have to be updated to the newest version which doesnt have support for VS2017. The way around this would either be two different pages for the extension or just manual install for VS2017.

**Comment by DrEthan77** [comment]
@MarkRobinsonHERE @jedmao that being said we should probably update the build requirements to only allow .17 instead of .15-.17 (.15 and .16 equal VS2015 and VS2017)

**Comment by MarkRobinsonHERE** [comment]
Problem is my VS2017 automatically updated from the marketplace and now the extension is hosed. :(

**Comment by DrEthan77** [comment]
@MarkRobinsonHERE yeah i would uninstall the extension from the marketplace rn and then build it yourself in your setup, this only until we can change the stuff.

**Pull request merged**
